apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: app-argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: microservice-1
                - service: microservice-2
                - service: microservice-3
          - list:
              elements:
                - env: dev
                - env: tst
                - env: uat
                - env: prod
  template:
    metadata:
      name: '{{service}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-gitops-repo.git
        targetRevision: main
        path: gitops/charts/app-chart
        helm:
          valueFiles:
            - ../../microservices/{{service}}/{{env}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
