name: Terraform Runner
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init
      - name: Terraform Apply
        working-directory: ${{ inputs.working-directory }}
        run: terraform apply -auto-approve -var-file=${{ inputs.environment }}.tfvars
